version: "2"
services:
  server:
    image: diego10rocha/pbl3_redes:banco_do_brasil_bridge_final
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /app
    ports:
      - "8017:8017/tcp"
    network_mode: "bridge"